Temporary fix for vectorized nacelles.
https://github.com/OpenMDAO/Aviary/blob/67c45b9d10943bc2360f344ceffe5d4f5f54a75b/aviary/subsystems/mass/mass_builder.py#L166

I got it to run and converge but I am running into an error here in
mass_builder.py:166

num_engines = [2, 1]

np.dot(val, num_engines)[0]

returns:

Traceback (most recent call last):
File "<string>", line 1, in <module>
IndexError: invalid index to scalar variable.

Note that 'val' = [0, 0] which is the nacelle mass

There are two issues:
1. The dot product returns an integer if nacelle mass (val) are entered
   as "0" instead of "0.0"
2. If val is a list of floats, the dot product is still a float that
   cannot be indexed.